name: libras_quiz
description: Libras Quiz

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # database
  shared_preferences: ^2.0.20
  get_it: ^7.6.4

  # state management
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.4
  provider: ^6.0.5
  kartal: ^3.4.1

  #FIREBASE
  firebase_core: ^2.16.0
  firebase_analytics: ^10.4.4
  firebase_crashlytics: ^3.3.4
  firebase_performance: ^0.9.2+4

  #UI
  flutter_launcher_icons: ^0.11.0
  gif: ^2.2.0
  fluttertoast: ^8.2.2
  google_fonts:
  flutter_spinkit: ^5.2.0

  # ux

  dropdown_button2: ^2.3.9

  # core utilities
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1

  #Google
  google_sign_in: ^6.1.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_splash.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/gifs/numeros/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages